name:  buildfork
  
on:
  workflow_dispatch:

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name:  checkout
        uses:  actions/checkout@v4
      - name:  cache
        uses:  actions/cache@4.1.2
        with:
          path:  ~/.npm
          key:  buildCache
      - run:  npm ci
      - run:  npm test -- --coverage
        env:
          CI: true
      - name:  upload code coverage
        uses:  actions/upload-artifact@v4.3.2
        with:
          name:  codecoverage
          path:  coverage
      - name:  build
        run:  npm run build
      - name: upload build files
        uses:  actions/upload-artifact@v4.3.2
        with:
          name:  build
          path:  build

    
